vich_uploader:
    db_driver: orm
    mappings:
        article_image:
            uri_prefix: /images/vehicle
            upload_destination: '%kernel.project_dir%/public/img/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

